project:
  type: website
  output-dir: docs

website:
  title: "Denise Cammarota"
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Sobre mim
        href: about.qmd
      #- text: Pesquisa
      #  href: research.qmd
      - text: Blog
        href: blog/index.qmd
      #- text: Projetos
      #  href: projects/index.qmd
      #- text: Notas
      #  href: notes.qmd
    right:
      - icon: github
        href: https://github.com/denisecammarota

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

