---
title: "Sobre mim"
toc: false
---

Sou doutoranda em Física no Instituto de Física Teórica da UNESP (IFT-UNESP), em São Paulo. Tenho competências em ciência e análise de dados, programação e modelagem matemática, que gosto de aplicar a problemas do meu interesse. Meu trabalho de pesquisa está atualmente situado na interface entre modelagem matemática, epidemiologia e ciência e análise de dados, com foco em compreender os mecanismos por trás da dinâmica de doenças infecciosas e em desenvolver e aplicar métodos quantitativos nas áreas de saúde pública e vigilância epidemiológica.

<br>

::: columns
::: {.column width="55%"}
## Trajetória académica

**Doutorado (PhD) em Física**\
Instituto de Física Teórica --- UNESP\
Agosto de 2022 -- presente

*Tese:* Modelagem matemática de doenças tropicais com heterogeneidades

<br>

**Mestrado em Física**\
Instituto Balseiro --- Argentina\
Fevereiro de 2021 -- fevereiro de 2022

*Tese:* Modelos epidemiológicos de COVID-19: simulações computacionais, estatística bayesiana e técnicas de aprendizado de máquina

<br>

**Graduação em Física**\
Instituto Balseiro --- Argentina\
Agosto de 2018 -- fevereiro de 2021

*Dissertação:* Modelos epidemiológicos de COVID-19: simulações computacionais, estatística bayesiana e técnicas de aprendizado de máquina
:::

::: {.column width="45%"}
## Skills

### Métodos

-   análise de dados (ETL, painéis, relatórios)
-   ciência de dados
-   machine learning e deep learning
-   machine learning científico
-   modelagem matemática de doenças infecciosas
-   modelos de equações diferenciais
-   álgebra linear aplicada

<br>

### Programação

-   Python\
-   R\
-   SQL\
-   C/C++

<br>

### Stack principal

-   numpy, pandas, matplotlib, seaborn\
-   scikit-learn, tensorflow\
-   tidyverse (dplyr, ggplot2, purrr)\
-   shiny, quarto
:::
:::
